### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by chirayudesai**
I have already created an android10 branch which has the contents of current master.

This branch will now be the primary development branch.
Old master aka current android10 will become the stable branch.
android11 will be created when that's out and the targeted release, and that will make it easier to do breaking changes if ever needed.

### CODE REVIEW

**Comment by chirayudesai** [comment]
#98 is being tested one last time by @mikeNG to make sure it all works for sure.

we can them remove prebuilts.

**Comment by chirayudesai** [comment]
> #98 is being tested one last time by @mikeNG to make sure it all works for sure.
Done
> 
> we can then remove prebuilts.
https://github.com/stevesoltys/seedvault/pull/119

**Comment by chirayudesai** [comment]
https://github.com/chirayudesai/backup/commits/master-merge-develop

This is what a merge looks like
Steps:
1. git checkout -b master-merge-develop upstream/master
2. git merge upstream/develop

**Comment by grote** [comment]
Can we merge this now and delete `develop` afterwards?

**Comment by chirayudesai** [comment]
@stevesoltys can you mark this as approved? It won't let me push without that. Thanks!

**Review by stevesoltys — APPROVED** [review]

**Comment by chirayudesai** [comment]
https://github.com/stevesoltys/seedvault/pull/124

**Pull request closed without merging**
