### PR TITLE
Merge master into android10

### PR DESCRIPTION
**Pull request by chirayudesai**
`master-android10` is basically master as it exists right now, so that we have a copy of it pre android11 for merging into the stable branch.

### CODE REVIEW

**Comment by chirayudesai** [comment]
Needs some testing, but should be fine for the most part.

Some of these improvements would be really nice to ship on android10.

**Comment by chirayudesai** [comment]
We could also do a release now or after this is merged @stevesoltys

**Comment by chirayudesai** [comment]
Set to draft pending testing.

**Comment by chirayudesai** [comment]
We should also pick https://github.com/stevesoltys/seedvault/pull/133/commits/8f6de0f45eeaa64b24b43fc0d590c256eb3e1f44
"Fix lint issues with translations and ignore missing translations …" once merged.

**Comment by stevesoltys** [comment]
@chirayudesai 

Sure, I will move the repository to the new organization and create a release all in one go. I should be able to get that stuff done on Sunday if this is merged by then.

**Comment by mikeNG** [comment]
Tested multiple backup & restore on jasmine and sargo, current android10 to new and new to new, didn't notice any regressions.

**Review by nickcalyx — APPROVED** [review]

**Pull request merged**
